// Database model types
// These will be generated by Prisma, but we can define additional types here

export interface DatabaseUser {
  id: string
  email: string
  name: string
  passwordHash: string
  avatar?: string
  emailVerified: boolean
  createdAt: Date
  updatedAt: Date
}

export interface CreateUserData {
  email: string
  name: string
  passwordHash: string
}

export interface UpdateUserData {
  name?: string
  avatar?: string
  emailVerified?: boolean
}
